CREATE DATABASE IF NOT EXISTS bk_db;
USE bk_db;
CREATE USER IF NOT EXISTS 'bk_dev'@'localhost' IDENTIFIED BY 'BK@123Pwd';
GRANT ALL PRIVILEGES ON bk_db.* TO 'bk_dev'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
